name: extenso
description: Plugin para converter números para texto por extenso em português.
version: 1.0.0
repository: https://github.com/gerbertsantos/extenso
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  # Nenhuma dependência externa necessária

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
